const buses = [
    
    // ---- Extra 10 buses ----
    // {
    //     operator: "humsafar travels",
    //     from: "Solapur",
    //     to: "Indore",
    //     departure: "06:00 AM",
    //     duration: 4,
    //     price: 650,
    //     seats: 22,
    //     pickups: ["solapur station", "Kashmiri Gate"],
    //     drops: ["Dmart darga", "CBS stand"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Rajdhani Express Buses",
    //     from: "Jaipur",
    //     to: "Delhi",
    //     departure: "07:30 AM",
    //     duration: 5,
    //     price: 750,
    //     seats: 40,
    //     pickups: ["Jaipur Station", "Sindhi Camp"],
    //     drops: ["Delhi ISBT", "Kashmiri Gate"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Southway Travels",
    //     from: "Chennai",
    //     to: "Madurai",
    //     departure: "09:00 PM",
    //     duration: 8,
    //     price: 950,
    //     seats: 30,
    //     pickups: ["Chennai Central", "Chennai Egmore"],
    //     drops: ["Madurai Junction", "Madurai Bus Stand"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Western Star",
    //     from: "Ahmedabad",
    //     to: "Surat",
    //     departure: "05:30 PM",
    //     duration: 6,
    //     price: 700,
    //     seats: 35,
    //     pickups: ["Ahmedabad Bus Stand", "Ahmedabad Railway Station"],
    //     drops: ["Surat Station", "Surat Bus Stand"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Royal Cruiser",
    //     from: "Kolkata",
    //     to: "Digha",
    //     departure: "06:45 AM",
    //     duration: 5,
    //     price: 500,
    //     seats: 28,
    //     pickups: ["Kolkata Esplanade", "Howrah"],
    //     drops: ["Digha Bus Stand", "Digha Sea Beach"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Himalaya Travels",
    //     from: "Dehradun",
    //     to: "Haridwar",
    //     departure: "02:00 PM",
    //     duration: 3,
    //     price: 400,
    //     seats: 30,
    //     pickups: ["Dehradun Station", "ISBT Dehradun"],
    //     drops: ["Haridwar Station", "Haridwar Bus Stand"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Ocean Line",
    //     from: "Visakhapatnam",
    //     to: "Bhubaneswar",
    //     departure: "11:00 PM",
    //     duration: 9,
    //     price: 1100,
    //     seats: 36,
    //     pickups: ["Vizag Station", "Vizag Bus Stand"],
    //     drops: ["Bhubaneswar Station", "Bhubaneswar Airport"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Desert King",
    //     from: "Jodhpur",
    //     to: "Udaipur",
    //     departure: "04:15 PM",
    //     duration: 7,
    //     price: 800,
    //     seats: 26,
    //     pickups: ["Jodhpur Station", "Jodhpur Airport"],
    //     drops: ["Udaipur Station", "Udaipur Bus Stand"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Green Valley Travels",
    //     from: "Guwahati",
    //     to: "Shillong",
    //     departure: "07:45 AM",
    //     duration: 5,
    //     price: 700,
    //     seats: 33,
    //     pickups: ["Guwahati Station", "Paltan Bazar"],
    //     drops: ["Shillong Police Bazar", "Shillong Bus Stand"],
    //     bookedSeats: []
    // },
    // {
    //     operator: "Express Link",
    //     from: "Patna",
    //     to: "Ranchi",
    //     departure: "06:30 PM",
    //     duration: 7,
    //     price: 850,
    //     seats: 30,
    //     pickups: ["Patna Station", "Patna Airport"],
    //     drops: ["Ranchi Station", "Ranchi Bus Stand"],
    //     bookedSeats: []
    // }
    // ---- Existing 10 buses (your code above) ----
    {
        operator: "humsafar travels",
        from: "Solapur",
        to: "Indore",
        departure: "06:00 AM",
        duration: 4,
        price: 650,
        seats: 22,
        pickups: ["Solapur Station", "Kashmiri Gate"],
        drops: ["Dmart Darga", "CBS Stand"],
        bookedSeats: []
    },
    {
        operator: "Rajdhani Express Buses",
        from: "Jaipur",
        to: "Delhi",
        departure: "07:30 AM",
        duration: 5,
        price: 750,
        seats: 40,
        pickups: ["Jaipur Station", "Sindhi Camp"],
        drops: ["Delhi ISBT", "Kashmiri Gate"],
        bookedSeats: []
    },
    {
        operator: "Southway Travels",
        from: "Chennai",
        to: "Madurai",
        departure: "09:00 PM",
        duration: 8,
        price: 950,
        seats: 30,
        pickups: ["Chennai Central", "Chennai Egmore"],
        drops: ["Madurai Junction", "Madurai Bus Stand"],
        bookedSeats: []
    },
    {
        operator: "Western Star",
        from: "Ahmedabad",
        to: "Surat",
        departure: "05:30 PM",
        duration: 6,
        price: 700,
        seats: 35,
        pickups: ["Ahmedabad Bus Stand", "Ahmedabad Railway Station"],
        drops: ["Surat Station", "Surat Bus Stand"],
        bookedSeats: []
    },
    {
        operator: "Royal Cruiser",
        from: "Kolkata",
        to: "Digha",
        departure: "06:45 AM",
        duration: 5,
        price: 500,
        seats: 28,
        pickups: ["Kolkata Esplanade", "Howrah"],
        drops: ["Digha Bus Stand", "Digha Sea Beach"],
        bookedSeats: []
    },
    {
        operator: "Himalaya Travels",
        from: "Dehradun",
        to: "Haridwar",
        departure: "02:00 PM",
        duration: 3,
        price: 400,
        seats: 30,
        pickups: ["Dehradun Station", "ISBT Dehradun"],
        drops: ["Haridwar Station", "Haridwar Bus Stand"],
        bookedSeats: []
    },
    {
        operator: "Ocean Line",
        from: "Visakhapatnam",
        to: "Bhubaneswar",
        departure: "11:00 PM",
        duration: 9,
        price: 1100,
        seats: 36,
        pickups: ["Vizag Station", "Vizag Bus Stand"],
        drops: ["Bhubaneswar Station", "Bhubaneswar Airport"],
        bookedSeats: []
    },
    {
        operator: "Desert King",
        from: "Jodhpur",
        to: "Udaipur",
        departure: "04:15 PM",
        duration: 7,
        price: 800,
        seats: 26,
        pickups: ["Jodhpur Station", "Jodhpur Airport"],
        drops: ["Udaipur Station", "Udaipur Bus Stand"],
        bookedSeats: []
    },
    {
        operator: "Green Valley Travels",
        from: "Guwahati",
        to: "Shillong",
        departure: "07:45 AM",
        duration: 5,
        price: 700,
        seats: 33,
        pickups: ["Guwahati Station", "Paltan Bazar"],
        drops: ["Shillong Police Bazar", "Shillong Bus Stand"],
        bookedSeats: []
    },
    {
        operator: "Express Link",
        from: "Patna",
        to: "Ranchi",
        departure: "06:30 PM",
        duration: 7,
        price: 850,
        seats: 30,
        pickups: ["Patna Station", "Patna Airport"],
        drops: ["Ranchi Station", "Ranchi Bus Stand"],
        bookedSeats: []
    },

    // ---- 20 New Buses ----
    {
        operator: "Skyline Travels",
        from: "Mumbai",
        to: "Pune",
        departure: "08:00 AM",
        duration: 4,
        price: 600,
        seats: 40,
        pickups: ["Mumbai Central", "Borivali"],
        drops: ["Pune Station", "Shivaji Nagar"],
        bookedSeats: []
    },
    {
        operator: "Shatabdi Travels",
        from: "Lucknow",
        to: "Kanpur",
        departure: "09:15 AM",
        duration: 3,
        price: 350,
        seats: 25,
        pickups: ["Lucknow Charbagh", "Alambagh"],
        drops: ["Kanpur Central", "Rawatpur"],
        bookedSeats: []
    },
    {
        operator: "Blue Line",
        from: "Nagpur",
        to: "Bhopal",
        departure: "10:00 PM",
        duration: 8,
        price: 900,
        seats: 32,
        pickups: ["Nagpur Station", "Nagpur Airport"],
        drops: ["Bhopal Junction", "Bhopal ISBT"],
        bookedSeats: []
    },
    {
        operator: "Sunrise Express",
        from: "Hyderabad",
        to: "Vijayawada",
        departure: "06:30 AM",
        duration: 6,
        price: 700,
        seats: 34,
        pickups: ["Hyderabad Station", "LB Nagar"],
        drops: ["Vijayawada Station", "Benz Circle"],
        bookedSeats: []
    },
    {
        operator: "Falcon Travels",
        from: "Delhi",
        to: "Agra",
        departure: "01:00 PM",
        duration: 4,
        price: 500,
        seats: 28,
        pickups: ["Delhi ISBT", "Kashmiri Gate"],
        drops: ["Agra Cantt", "Agra Fort"],
        bookedSeats: []
    },
    {
        operator: "Eagle Express",
        from: "Chandigarh",
        to: "Amritsar",
        departure: "05:00 PM",
        duration: 6,
        price: 650,
        seats: 30,
        pickups: ["Chandigarh ISBT", "Sector 17"],
        drops: ["Amritsar Station", "Golden Temple"],
        bookedSeats: []
    },
    {
        operator: "Coastal Line",
        from: "Mangalore",
        to: "Goa",
        departure: "07:45 PM",
        duration: 9,
        price: 1200,
        seats: 38,
        pickups: ["Mangalore Station", "Mangalore KSRTC"],
        drops: ["Panaji", "Madgaon"],
        bookedSeats: []
    },
    {
        operator: "Northern Star",
        from: "Varanasi",
        to: "Gorakhpur",
        departure: "11:00 AM",
        duration: 5,
        price: 550,
        seats: 26,
        pickups: ["Varanasi Cantt", "Manduadih"],
        drops: ["Gorakhpur Station", "Gorakhpur Bus Stand"],
        bookedSeats: []
    },
    {
        operator: "Metro Travels",
        from: "Bengaluru",
        to: "Mysuru",
        departure: "06:00 AM",
        duration: 4,
        price: 450,
        seats: 36,
        pickups: ["Majestic", "Yeshwanthpur"],
        drops: ["Mysuru Station", "Mysuru Bus Stand"],
        bookedSeats: []
    },
    {
        operator: "Royal Star",
        from: "Delhi",
        to: "Chandigarh",
        departure: "07:00 AM",
        duration: 5,
        price: 700,
        seats: 40,
        pickups: ["Kashmiri Gate", "Delhi ISBT"],
        drops: ["Chandigarh ISBT", "Sector 43"],
        bookedSeats: []
    },
    {
        operator: "Speedlink Travels",
        from: "Indore",
        to: "Bhopal",
        departure: "03:30 PM",
        duration: 4,
        price: 500,
        seats: 28,
        pickups: ["Indore Sarwate", "Vijay Nagar"],
        drops: ["Bhopal ISBT", "Bhopal Junction"],
        bookedSeats: []
    },
    {
        operator: "Classic Travels",
        from: "Nagpur",
        to: "Raipur",
        departure: "08:00 AM",
        duration: 5,
        price: 600,
        seats: 30,
        pickups: ["Nagpur Central", "Sitabuldi"],
        drops: ["Raipur Station", "Raipur Bus Stand"],
        bookedSeats: []
    },
    {
        operator: "Fast Wheels",
        from: "Surat",
        to: "Vadodara",
        departure: "02:00 PM",
        duration: 4,
        price: 450,
        seats: 24,
        pickups: ["Surat Bus Stand", "Ring Road"],
        drops: ["Vadodara Junction", "Vadodara Central"],
        bookedSeats: []
    },
    {
        operator: "Silver Line",
        from: "Lucknow",
        to: "Varanasi",
        departure: "10:00 PM",
        duration: 7,
        price: 800,
        seats: 36,
        pickups: ["Lucknow Charbagh", "Alambagh"],
        drops: ["Varanasi Cantt", "Varanasi Station"],
        bookedSeats: []
    },
    {
        operator: "Pearl Travels",
        from: "Chennai",
        to: "Coimbatore",
        departure: "09:30 PM",
        duration: 9,
        price: 950,
        seats: 40,
        pickups: ["Chennai Egmore", "Tambaram"],
        drops: ["Coimbatore Junction", "Gandhipuram"],
        bookedSeats: []
    },
    {
        operator: "Green Express",
        from: "Thiruvananthapuram",
        to: "Kochi",
        departure: "07:00 AM",
        duration: 6,
        price: 700,
        seats: 32,
        pickups: ["Trivandrum Central", "East Fort"],
        drops: ["Ernakulam Junction", "Kochi Vyttila"],
        bookedSeats: []
    },
    {
        operator: "Rainbow Travels",
        from: "Pune",
        to: "Nashik",
        departure: "11:00 AM",
        duration: 5,
        price: 550,
        seats: 28,
        pickups: ["Pune Station", "Swargate"],
        drops: ["Nashik Road", "CBS Nashik"],
        bookedSeats: []
    },
    {
        operator: "Capital Express",
        from: "Delhi",
        to: "Lucknow",
        departure: "08:00 PM",
        duration: 9,
        price: 1000,
        seats: 42,
        pickups: ["Kashmiri Gate", "Delhi ISBT"],
        drops: ["Lucknow Charbagh", "Alambagh"],
        bookedSeats: []
    },
    {
        operator: "Southern Breeze",
        from: "Hyderabad",
        to: "Chennai",
        departure: "09:00 PM",
        duration: 10,
        price: 1200,
        seats: 38,
        pickups: ["Hyderabad Station", "MGBS"],
        drops: ["Chennai Central", "Tambaram"],
        bookedSeats: []
    },
    {
        operator: "Golden Travels",
        from: "Patna",
        to: "Varanasi",
        departure: "06:00 AM",
        duration: 6,
        price: 650,
        seats: 30,
        pickups: ["Patna Station", "Patna Airport"],
        drops: ["Varanasi Cantt", "Varanasi Junction"],
        bookedSeats: []
    }


];

module.exports = buses;